# Generated by Django 4.0.4 on 2022-04-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=255, verbose_name='دامنه سایت')),
                ('address', models.CharField(max_length=255, verbose_name='ادرس سایت')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='تلفن سایت')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='فاکس سایت')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن کپی رایت سایت')),
                ('copy_right', models.CharField(max_length=255, verbose_name='دامنه سایت')),
                ('about_us_text', models.TextField(verbose_name=' متن درباره ما سایت')),
                ('site_logo', models.ImageField(upload_to='images/site_setting/', verbose_name='لوگوی سایت')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنضیمات سایت ',
                'verbose_name_plural': ' تنظیمات',
            },
        ),
    ]
