# Generated by Django 4.0.4 on 2022-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_alter_sitesetting_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('url', models.TextField(max_length=255, verbose_name='ادرس')),
                ('url_title', models.TextField(max_length=255, verbose_name='لینک')),
                ('description', models.TextField(max_length=255, verbose_name='توضیحات  اسلایدر')),
                ('image', models.ImageField(upload_to='images/sliders', verbose_name='تصویر اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
