# Generated by Django 4.0.4 on 2022-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیر فعال'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.CharField(max_length=150, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url_title',
            field=models.CharField(max_length=100, verbose_name=' عنوان لینک '),
        ),
    ]
