# Generated by Django 4.0.4 on 2022-04-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_article_created_date_alter_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='selected_category',
            new_name='selected_categories',
        ),
    ]
